import os
from dotenv import load_dotenv

load_dotenv()
# Also try loading from parent directory if not found
load_dotenv(os.path.join(os.path.dirname(__file__), '..', '.env'))

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
ALLOWED_USER_ID = int(os.getenv("ALLOWED_USER_ID", 0))

RCON_HOST = os.getenv("RCON_HOST", "cs2")
RCON_PORT = int(os.getenv("RCON_PORT", 27015))
RCON_PASSWORD = os.getenv("RCON_PASSWORD")
CS2_PASSWORD = os.getenv("CS2_PASSWORD", "Unknown")
CS2_SERVERNAME = os.getenv("CS2_SERVERNAME", "Counter-Strike 2")

if not RCON_PASSWORD:
    print("WARNING: RCON_PASSWORD is not set! RCON commands will fail.")

# Map Catalog
MAPS = {
    "1v1aim_map_longdustversion_d": "workshop/3082605693/1v1aim_map_longdustversion_d",
    "aim_ag_texture2": "workshop/3074961197/aim_ag_texture2",
    "aim_ag_texture_city_advanced": "workshop/3082113929/aim_ag_texture_city_advanced",
    "aim_ag_texture_jungle": "workshop/3095778105/aim_ag_texture_jungle",
    "aim_deagle": "workshop/3075996446/aim_deagle",
    "aim_map": "workshop/3084291314/aim_map",
    "aim_redline_fp": "workshop/3070253400/aim_redline_fp",
    "aim_theorem": "workshop/3070348309/aim_theorem",
    "aim_usp": "workshop/3085962528/aim_usp",
    "ar_baggage": "ar_baggage",
    "ar_churches_s2r": "workshop/3070291913/ar_churches_s2r",
    "ar_dizzy": "workshop/3070553020/ar_dizzy",
    "ar_pool_day": "ar_pool_day",
    "ar_shoots": "ar_shoots",
    "ar_shoots_night": "ar_shoots_night",
    "as_oilrig": "workshop/3104677430/as_oilrig",
    "awp_bhop_rocket": "workshop/3142070597/awp_bhop_rocket",
    "battleball": "workshop/3280650663/battleball",
    "bhop_1derland": "workshop/3077596014/bhop_1derland",
    "bhop_arcturus": "workshop/3088973190/bhop_arcturus",
    "bhop_at_night": "workshop/3077211069/bhop_at_night",
    "bhop_cherryblossom": "workshop/3082038560/bhop_cherryblossom",
    "bhop_kiwi_cwfx": "workshop/3095219437/bhop_kiwi_cwfx",
    "bhop_ragnarok": "workshop/3077153735/bhop_ragnarok",
    "bhop_whiteshit": "workshop/3078523849/bhop_whiteshit",
    "bhop_zunron": "workshop/3077475505/bhop_zunron",
    "br_electrified": "workshop/3330484099/br_electrified",
    "br_flood": "workshop/3267454508/br_flood",
    "br_stacks": "workshop/3297489255/br_stacks",
    "br_t2": "workshop/3462095803/br_t2",
    "cr_devisland_p1_v1": "workshop/3076483842/cr_devisland_p1_v1",
    "cr_minecraft_jb_v2": "workshop/3070896876/cr_minecraft_jb_v2",
    "cs2_bloodstrike": "workshop/3071890065/cs2_bloodstrike",
    "cs_agency": "cs_agency",
    "cs_assault": "workshop/3070594412/cs_assault",
    "cs_assult_classic": "workshop/3215705579/cs_assult_classic",
    "cs_insertion2": "workshop/3236615060/cs_insertion2",
    "cs_italy": "cs_italy",
    "cs_italy_classic": "workshop/3212419403/cs_italy_classic",
    "cs_militia": "workshop/3089953774/cs_militia",
    "cs_militia_classic": "workshop/3144773563/cs_militia_classic",
    "cs_office": "cs_office",
    "cs_office_classic": "workshop/3216844784/cs_office_classic",
    "ctf_2fort": "workshop/3555531615/ctf_2fort",
    "ctf_doublecross": "workshop/3555532817/ctf_doublecross",
    "ctf_turbine": "workshop/3555534037/ctf_turbine",
    "daymare": "workshop/3072640420/daymare",
    "de_akiba": "workshop/3108513658/de_akiba",
    "de_ancient": "de_ancient",
    "de_ancient_night": "de_ancient_night",
    "de_anubis": "de_anubis",
    "de_anubis_silly": "workshop/3245985233/de_anubis_silly",
    "de_assembly": "workshop/3071005299/de_assembly",
    "de_aztec_classic": "workshop/3213800338/de_aztec_classic",
    "de_aztec_hr": "workshop/3079692971/de_aztec_hr",
    "de_bank": "workshop/3070581293/de_bank",
    "de_basalt": "workshop/3329258290/de_basalt",
    "de_biome": "workshop/3075706807/de_biome",
    "de_brewery": "de_brewery",
    "de_cache": "workshop/3437809122/de_cache",
    "de_cbble": "workshop/3329387648/de_cbble",
    "de_dogtown": "de_dogtown",
    "de_dust2": "de_dust2",
    "de_dust2_classic": "workshop/3201205818/de_dust2_classic",
    "de_dust2_wingman": "workshop/3413800427/de_dust2_wingman",
    "de_dust_classic": "workshop/3078095785/de_dust_classic",
    "de_edin": "workshop/3328169568/de_edin",
    "de_ema": "workshop/3386116667/de_ema",
    "de_grail": "de_grail",
    "de_indoor": "workshop/3535917558/de_indoor",
    "de_inferno": "de_inferno",
    "de_inferno_prophunt": "workshop/3348038890/de_inferno_prophunt",
    "de_jura": "de_jura",
    "de_lake": "workshop/3070563536/de_lake",
    "de_memento": "workshop/3165559377/de_memento",
    "de_mills": "workshop/3152430710/de_mills",
    "de_mirage": "de_mirage",
    "de_mirage45": "workshop/3270516952/de_mirage45",
    "de_mirage_bricks": "workshop/3464733042/de_mirage_bricks",
    "de_mirage_d": "workshop/3402437047/de_mirage_d",
    "de_mirage_prophunt": "workshop/3287578956/de_mirage_prophunt",
    "de_mutiny": "workshop/3070766070/de_mutiny",
    "de_nuke": "de_nuke",
    "de_nuke_classic": "workshop/3205793205/de_nuke_classic",
    "de_nuke_prophunt": "workshop/3366748499/de_nuke_prophunt",
    "de_nuke_silly": "workshop/3245245780/de_nuke_silly",
    "de_overpass": "de_overpass",
    "de_overpass_45": "workshop/3270066070/de_overpass_45",
    "de_overpass_prophunt": "workshop/3382166635/de_overpass_prophunt",
    "de_palais": "workshop/3257582863/de_palais",
    "de_pipeline": "workshop/3079872050/de_pipeline",
    "de_rats_remake": "workshop/3460962520/de_rats_remake",
    "de_rooftop": "workshop/3536622725/de_rooftop",
    "de_ruins_d_prefab": "workshop/3072352643/de_ruins_d_prefab",
    "de_safehouse": "workshop/3070550406/de_safehouse",
    "de_sakura": "workshop/3082340867/de_sakura",
    "de_season": "workshop/3073892687/de_season",
    "de_shortdust": "workshop/3070612859/de_shortdust",
    "de_survivor_classic_m": "workshop/3217247541/de_survivor_classic_m",
    "de_thera": "workshop/3121217565/de_thera",
    "de_train": "workshop/3070284539/de_train",
    "de_train_twyxe": "workshop/3406937162/de_train_twyxe",
    "de_vertigo": "de_vertigo",
    "de_vertigo_45": "workshop/3276886893/de_vertigo_45",
    "de_vertigo_prophunt": "workshop/3292648008/de_vertigo_prophunt",
    "de_whistle": "workshop/3308613773/de_whistle",
    "deathrun_civilization": "workshop/3188021118/deathrun_civilization",
    "deathrun_egypt": "workshop/3311285877/deathrun_egypt",
    "deathrun_iceworld_cs2": "workshop/3083325292/deathrun_iceworld_cs2",
    "deathrun_playground": "workshop/3164611860/deathrun_playground",
    "ewii_challenge": "workshop/3170668869/ewii_challenge",
    "field": "workshop/3238565662/field",
    "freebet_aim_map": "workshop/3146122036/freebet_aim_map",
    "fun_bounce": "workshop/3088183343/fun_bounce",
    "fy_iceworld": "workshop/3070238628/fy_iceworld",
    "fy_pool_day": "workshop/3070923343/fy_pool_day",
    "gd_rialto": "workshop/3085490518/gd_rialto",
    "gg_lego_arena": "workshop/3267768230/gg_lego_arena",
    "gg_simpsons_vs_flanders_v2": "workshop/3109232789/gg_simpsons_vs_flanders_v2",
    "gulag": "workshop/3326465469/gulag",
    "hellcasecyrilchallenge": "workshop/3145779590/hellcasecyrilchallenge",
    "kloce": "workshop/3248340515/kloce",
    "kz_checkmate": "workshop/3070194623/kz_checkmate",
    "kz_dima": "workshop/3343029934/kz_dima",
    "kz_ggsh": "workshop/3072744536/kz_ggsh",
    "kz_ltt": "workshop/3072699538/kz_ltt",
    "kz_nomibo": "workshop/3077122656/kz_nomibo",
    "kz_rc_stonehenge": "workshop/3072219045/kz_rc_stonehenge",
    "kz_rc_twotowers": "workshop/3083509404/kz_rc_twotowers",
    "kz_simplyhard": "workshop/3078311932/kz_simplyhard",
    "kz_sxb2_biewan": "workshop/3076000218/kz_sxb2_biewan",
    "kz_sxb2_cxz": "workshop/3083714192/kz_sxb2_cxz",
    "kz_victoria": "workshop/3086304337/kz_victoria",
    "mcdonalds": "workshop/3134466699/mcdonalds",
    "mg_acrophobia_run_v2": "workshop/3070463620/mg_acrophobia_run_v2",
    "mg_alley_course_v2": "workshop/3070455802/mg_alley_course_v2",
    "mg_circle_course_v3": "workshop/3070434475/mg_circle_course_v3",
    "mg_glave_course_v2": "workshop/3070445185/mg_glave_course_v2",
    "mg_lego_course_2": "workshop/3202752274/mg_lego_course_2",
    "mg_metal_course_v2": "workshop/3070464208/mg_metal_course_v2",
    "mg_metro_course_s2": "workshop/3071040020/mg_metro_course_s2",
    "mg_metro_course_v1": "workshop/3070463151/mg_metro_course_v1",
    "mg_office_course_v3": "workshop/3070459211/mg_office_course_v3",
    "mg_simpsons_course_v2": "workshop/3070447697/mg_simpsons_course_v2",
    "mg_skeet_multigames_v7": "workshop/3082120895/mg_skeet_multigames_v7",
    "mg_sky_realm_v3": "workshop/3070451616/mg_sky_realm_v3",
    "mg_sonic_course_v2": "workshop/3070452642/mg_sonic_course_v2",
    "mg_switch_course_v2": "workshop/3070439729/mg_switch_course_v2",
    "mg_warmcup_headshot": "workshop/3076765511/mg_warmcup_headshot",
    "minecraft": "workshop/3186779271/minecraft",
    "minecraft_hungergame": "workshop/3240933254/minecraft_hungergame",
    "mp_raid": "workshop/3070346180/mp_raid",
    "only_up": "workshop/3074758439/only_up",
    "paintit": "workshop/3360723913/paintit",
    "school_d_environment_prefab": "workshop/3343693110/school_d_environment_prefab",
    "scoutzknivez_pure_cs2": "workshop/3073929825/scoutzknivez_pure_cs2",
    "shipment_version_1_0": "workshop/3086555291/shipment_version_1_0",
    "skatepark": "workshop/3309665004/skatepark",
    "speedball": "workshop/3443206318/speedball",
    "surf_ace": "workshop/3088413071/surf_ace",
    "surf_beginner": "workshop/3070321829/surf_beginner",
    "surf_benevolent": "workshop/3098972556/surf_benevolent",
    "surf_boreas": "workshop/3133346713/surf_boreas",
    "surf_deathstar": "workshop/3080544577/surf_deathstar",
    "surf_kitsune": "workshop/3076153623/surf_kitsune",
    "surf_mesa_revo": "workshop/3076980482/surf_mesa_revo",
    "surf_nyx": "workshop/3129698096/surf_nyx",
    "surf_rookie": "workshop/3082548297/surf_rookie",
    "surf_ski_2": "workshop/3079877518/surf_ski_2",
    "surf_utopia_njv": "workshop/3073875025/surf_utopia_njv",
    "surf_whiteout": "workshop/3296258256/surf_whiteout",
    "trainingoutside": "workshop/3475270536/trainingoutside",
    "twofort_cs2": "workshop/3345551391/twofort_cs2",
}


# Game Modes
# (name, game_type, game_mode)
# Game Modes
# Map Name -> RCON Command
GAME_MODES = {
    "Casual": "exec casual.cfg",
    "Casual 16": "exec casual.cfg",
    "45": "exec casual.cfg",
    "Competitive": "exec valve-competitive.cfg; exec settings/disable_random_round.cfg; log on; mp_logdetail 3; mp_logmoney 1; mp_logshots 1; sv_logfile 1; sv_logbans 1; sv_logecho 1",
    "Wingman": "exec wingman.cfg",
    "Custom Deathmatch": "exec deathmatch.cfg",
    "Retakes": "exec retake.cfg",
    "Surf": "exec surf.cfg",
    "KZ": "exec kz.cfg",
    "Practice": "exec practice.cfg",
    "ScoutzKnivez": "exec scoutzknivez.cfg",
    "Soccer": "exec soccer.cfg",
    "Mini Games": "exec minigames.cfg",
    "One In The Chamber": "exec oitc.cfg",
    "Hide n Seek": "exec hns.cfg",
    "Deathrun": "exec deathrun.cfg",
    "Prefire practice": "exec prefire.cfg",
    "Arms Race": "exec valve-armsrace.cfg",
    "1v1": "exec 1v1.cfg",
    "Aim": "exec aim.cfg",
    "AWP": "exec awp.cfg",
    "Battle Ball": "exec battle.cfg",

    "BHop": "exec bhop.cfg",
    "Battle Royale": "exec br.cfg",
    "Course": "exec course.cfg",
    "Capture The Flag": "exec ctf.cfg",
    "Executes": "exec executes.cfg",
    "GunGame": "exec gg.cfg",
    "🎲 Random Rounds": "exec valve-competitive.cfg; exec settings/enable_random_round.cfg"
}

# Reverse lookup for status display
MODE_LOOKUP = {
    (0, 0): "Casual",
    (0, 1): "Competitive",
    (0, 2): "Wingman",
    (1, 0): "Arms Race",
    (1, 1): "Demolition",
    (1, 2): "Custom Deathmatch",
    (2, 0): "Training",
    (3, 0): "Custom",
}

# Map Filtering by Mode
MODE_MAPS = {
    "Casual 16": [
        "as_oilrig",
        "cs_assult_classic",
        "de_aztec_classic",
        "de_dust_classic",
        "de_dust2_classic",
        "cs_italy_classic",
        "cs_militia_classic",
        "de_nuke_classic",
        "cs_office_classic",
        "de_survivor_classic_m",
    ],
    "45": [
        "de_vertigo_45",
        "de_anubis_silly",
        "de_overpass_45",
        "de_nuke_silly",
        "de_mirage45",
        "de_train_twyxe",
    ],
    "Competitive": [
        "de_ancient",
        "de_anubis",
        "de_inferno",
        "de_mirage",
        "de_nuke",
        "de_dust2",
        "de_train",
        "de_vertigo",
        "cs_italy",
        "cs_office",
        "de_ancient_night",
        "de_overpass",
        "de_jura",
        "de_grail",
        "cs_agency",
        "de_basalt",
        "de_edin",
        "de_assembly",
        "de_cbble",
        "de_cache",
        "de_pipeline",
        "de_biome",
        "mp_raid",
        "de_mutiny",
        "cs_assault",
        "de_ruins_d_prefab",
        "cs_militia",
        "de_aztec_hr",
        "de_akiba",
        "cs_insertion2",
        "de_mills",
        "de_thera",
        "de_season",
        "de_ema",
        "twofort_cs2",
        "de_rats_remake",
        "de_mirage_bricks",
    ],
    "🎲 Random Rounds": [
        "de_ancient",
        "de_anubis",
        "de_inferno",
        "de_mirage",
        "de_nuke",
        "de_dust2",
        "de_train",
        "de_vertigo",
        "cs_italy",
        "cs_office",
        "de_ancient_night",
        "de_overpass",
        "de_jura",
        "de_grail",
        "cs_agency",
        "de_basalt",
        "de_edin",
        "de_assembly",
        "de_cbble",
        "de_cache",
        "de_pipeline",
        "de_biome",
        "mp_raid",
        "de_mutiny",
        "cs_assault",
        "de_ruins_d_prefab",
        "cs_militia",
        "de_aztec_hr",
        "de_akiba",
        "cs_insertion2",
        "de_mills",
        "de_thera",
        "de_season",
        "de_ema",
        "twofort_cs2",
        "de_rats_remake",
        "de_mirage_bricks",
    ],
    "Retakes": [
        "de_ancient",
        "de_anubis",
        "de_inferno",
        "de_mirage",
        "de_nuke",
        "de_dust2",
        "de_train",
        "de_overpass",
        "de_vertigo",
    ],
    "Prefire practice": [
        "de_ancient",
        "de_anubis",
        "de_inferno",
        "de_mirage",
        "de_nuke",
        "de_dust2",
        "de_train",
        "de_overpass",
        "de_vertigo",
    ],
    "Executes": [
        "de_mirage",
    ],
    "Wingman": [
        "de_dust2_wingman",
        "de_mirage_d",
        "cs_italy",
        "cs_office",
        "de_vertigo",
        "de_ancient",
        "de_ancient_night",
        "de_anubis",
        "de_inferno",
        "de_nuke",
        "de_train",
        "de_overpass",
        "ar_shoots",
        "ar_shoots_night",
        "ar_baggage",
        "de_brewery",
        "de_dogtown",
        "de_palais",
        "de_whistle",
        "gd_rialto",
        "de_rooftop",
        "de_safehouse",
        "de_lake",
        "de_bank",
        "de_shortdust",
        "de_assembly",
        "de_cbble",
        "de_cache",
        "de_pipeline",
        "de_biome",
        "mp_raid",
        "de_mutiny",
        "cs_assault",
        "de_ruins_d_prefab",
        "de_sakura",
        "de_memento",
        "skatepark",
        "de_ema",
        "paintit",
        "de_mirage_bricks",
    ],
    "Custom Deathmatch": [
        "de_vertigo",
        "de_dust2",
        "de_inferno",
        "de_mirage",
    ],
    "GunGame": [
        "ar_shoots",
        "ar_shoots_night",
        "ar_baggage",
        "ar_pool_day",
        "speedball",
        "gg_lego_arena",
        "de_indoor",
        "de_assembly",
        "fy_iceworld",
        "daymare",
        "mcdonalds",
        "aim_theorem",
        "de_safehouse",
        "de_lake",
        "de_bank",
        "fun_bounce",
        "1v1aim_map_longdustversion_d",
        "ar_churches_s2r",
        "aim_ag_texture_city_advanced",
        "trainingoutside",
        "shipment_version_1_0",
        "aim_ag_texture2",
        "aim_ag_texture_jungle",
        "cs2_bloodstrike",
        "gg_simpsons_vs_flanders_v2",
        "school_d_environment_prefab",
        "de_ema",
        "twofort_cs2",
        "paintit",
        "kloce",
        "gulag",
        "de_rats_remake",
        "de_mirage_bricks",
    ],
    "1v1": [
        "aim_redline_fp",
    ],
    "KZ": [
        "only_up",
        "kz_dima",
        "ewii_challenge",
        "hellcasecyrilchallenge",
        "kz_checkmate",
        "kz_victoria",
        "kz_rc_stonehenge",
        "kz_sxb2_cxz",
        "kz_rc_twotowers",
        "kz_simplyhard",
        "kz_nomibo",
        "kz_sxb2_biewan",
        "kz_ggsh",
        "kz_ltt",
    ],
    "Surf": [
        "surf_kitsune",
        "surf_utopia_njv",
        "surf_beginner",
        "surf_mesa_revo",
        "surf_deathstar",
        "surf_rookie",
        "surf_benevolent",
        "surf_ace",
        "surf_boreas",
        "surf_nyx",
        "surf_whiteout",
        "surf_ski_2",
    ],
    "Mini Games": [
        "mg_skeet_multigames_v7",
        "mg_lego_course_2",
        "mg_warmcup_headshot",
    ],
    "Battle Royale": [
        "br_t2",
        "br_electrified",
        "br_stacks",
        "br_flood",
        "minecraft",
        "minecraft_hungergame",
    ],
    "Deathrun": [
        "deathrun_playground",
        "deathrun_egypt",
        "deathrun_civilization",
        "deathrun_iceworld_cs2",
    ],
    "Course": [
        "cr_devisland_p1_v1",
        "mg_switch_course_v2",
        "cr_minecraft_jb_v2",
        "mg_metro_course_v1",
        "mg_alley_course_v2",
        "mg_glave_course_v2",
        "mg_office_course_v3",
        "mg_metal_course_v2",
        "mg_acrophobia_run_v2",
        "mg_metro_course_s2",
        "mg_circle_course_v3",
        "mg_simpsons_course_v2",
        "mg_sonic_course_v2",
        "mg_sky_realm_v3",
    ],
    "ScoutzKnivez": [
        "scoutzknivez_pure_cs2",
        "ar_dizzy",
    ],
    "Hide n Seek": [
        "de_nuke_prophunt",
        "de_overpass_prophunt",
        "de_inferno_prophunt",
        "de_vertigo_prophunt",
        "de_mirage_prophunt",
    ],
    "Soccer": [
        "field",
    ],
    "AWP": [
        "awp_bhop_rocket",
    ],
    "Battle Ball": [
        "battleball",
    ],
    "Aim": [
        "aim_map",
        "freebet_aim_map",
        "fy_pool_day",
        "aim_usp",
        "aim_deagle",
        "1v1aim_map_longdustversion_d",
    ],
    "BHop": [
        "bhop_at_night",
        "bhop_ragnarok",
        "bhop_zunron",
        "bhop_1derland",
        "bhop_whiteshit",
        "bhop_cherryblossom",
        "bhop_arcturus",
        "bhop_kiwi_cwfx",
    ],
    "Capture The Flag": [
        "ctf_2fort",
        "ctf_doublecross",
        "ctf_turbine",
    ],
}

# Derived Workshop Maps
WORKSHOP_MAPS = {k: v for k, v in MAPS.items() if v.startswith("workshop/")}
